steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/weather-client', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'functions', 'deploy', 'weather-client', '--runtime', 'python311', '--trigger-http', '--allow-unauthenticated']
images: ['gcr.io/$PROJECT_ID/weather-client']
