steps:
  # build app with Maven
- name: maven:3-eclipse-temurin-17
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
  dir: ${_DIR}
  # Build and tag using commit sha

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/duet-ai-storageservice', '.', '-f', 'Dockerfile']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/duet-ai-storageservice']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'duet-ai-dataservice',
         '--image', 'gcr.io/$PROJECT_ID/duet-ai-storageservice',
         '--region', 'us-central1',
         '--no-allow-unauthenticated']

options:
  logging: 'CLOUD_LOGGING_ONLY'
